[package]
name = "readable"
version = "0.2.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.71"
axum = { version = "0.6.18", features = ["headers"] }
sync_wrapper = "0.1.2"
readable-readability = "0.4.0"
tokio = { version = "1.28.0", features = ["full"]}
url = "2.3.1"
reqwest = "0.11.17"
chrono = "0.4.24"
kuchiki = "0.8.1"
shuttle-axum = { version = "0.28.0" }
shuttle-runtime = { version = "0.28.0" }
once_cell = "1.17.1"
tower-http = { version = "0.4.4", features = ["fs"] }

